### ISSUE TITLE
Faulty example code in README.md

### ISSUE THREAD

**Issue by Taschi120** [micromouseonline/BasicEncoder#4]
This repository's README contains the following code snippet:

```
void loop() {
  int encoder_change = encoder.get_change();
  if (encoder_change) {
    Serial.println(encoder.get_change());
  }      
}
```

As pointed out within the same readme, the Serial.println() command will always print a 0 here, because the first call to encoder.get_change() has reset the input counter.

The correct call would be "Serial.println(encoder_change);". Could you please correct this?

**Comment by micromouseonline** [comment]
Good point. Thank you.

I have edited the file as indicated.
