### ISSUE TITLE
Typo in BasicEncoder.h in initialization of m_previous_state

### ISSUE THREAD

**Issue by inetdavid** [micromouseonline/BasicEncoder#5]
Typo?

    m_previous_state - pin_state();

should be

    m_previous_state = pin_state();

**Comment by micromouseonline** [comment]
So it should!

Thank you for taking the time to notice and notify me.

I will change the file immediately. Feel free to close the issue at your leisure.

**Comment by inetdavid** [comment]
Looks good!

**Comment by inetdavid** [comment]
Don't forget to bump the version and do a new release.  That will allow the Arduino IDE to auto-update.  (I had to find the file and manually edit it.)
