### ISSUE TITLE
Add fucntion to preset "count" in the Library

### ISSUE THREAD

**Issue by sthenge** [micromouseonline/BasicEncoder#6]
This is  not an issue, but a suggestion.  I hope that this method of communication is not inappropriate.

I have an application that uses a rotary encoder to determine a set point for a PID controller. It has upper and lower limits for "count" of > 0 and < 250. I tried several different methods to keep track of this in my app, but kept running into various issues.  It seemed easier to just keep track of this in the library, at least, the value of "count'. So, I added a function to BasicEncoder.h that allows me to set the value of "count" in the library. This is what I came up with.

  void set_count(int ncount) {
    uint8_t sreg = SREG;  // save the current interrupt enable flag
    noInterrupts();
    m_change = 0;
    m_steps = ncount * m_steps_per_count;
    SREG = sreg;  // restore the previous interrupt enable flag state
  }
Then in my app I do this:

  if (encoder.get_count() < 0) {
    encoder.set_count(0);
  }
  if (encoder.get_count() > 250) {
    encoder.set_count(250);
  }
Note that I am doing a get_count() call, so the library maintains the value of "count" till a reset() is called. following this test, I call for the current value of "count" to continue processing in my app.

It might be possible to add min,max parameters to the begin function, but this works for me. 

Hope this might be a useful addition to the library or, at least, a useful addition for a resourceful user.

Thanks,

Bill

**Comment by micromouseonline** [comment]
Hi

Thank you for taking the trouble to get in touch.

I think I understand your issue. Before considering a change to the library though, might I suggest that you only use the get_change() method to find out how the encoder value has changed since the last call? Obviously I do not know anything about your application but could you do something like this if it is based on the  Arduino framework:

```
set_point = constrain(set_point + encoder.get_change(),0,250);
```

**Comment by sthenge** [comment]
Peter,Thanks for your feedback. Your suggestion just might work.  I tried something similar using get_change() but not in one constrain call.  I’ll have to give it a try.Thanks,Bill Stoner

**Comment by micromouseonline** [comment]
Let me know how it goes.

**Comment by sthenge** [comment]
> Let me know how it goes.

This is probably overkill, but thought I would share for any other user that might be having difficulty with rotary encoder set point control.

Yes it works, Peter,  with a minor change.   

Had to make the collection of the `encoder.get_change()` to  `... += encoder.get_change()...` to accumulate changes in the variable `newSetPoint` until the button is pushed to apply the new set point.  See my code below.

Interrupt call routines to service the rotary encoder and its push button.
```
// Timer Service to periodically read Rotary Encoder
void timer_service() {  
  encoder.service();
}

// Pin Change Interrupt to read Rotary Encoder Push button
void RotarySw() {  

  if (digitalRead(PIN_SW) == 1)
    encoder_btn_count++;  // Increment the values
  if (encoder_btn_count > 2) encoder_btn_count = 2;
}

// Routine to get a new set point.  First thing checked with called from the "Loop()" routine each cycle.

void myEncoder() {

newSetPoint = constrain(newSetPoint += encoder.get_change(), 0, 250);


//Single push means set the new set point only if there is a new set point different than the current set point.
// This allows for a second tap of the push button to trigger a complete shutdown.

  if (setPoint != newSetPoint && encoder_btn_count == 1) {  
    setPoint = newSetPoint;                               
    encoder_btn_count = 0;
  }

//Double push of push button means shutdown - NOW! Reset everything to 0.
  if (encoder_btn_count == 2) {  
    setPoint = newSetPoint = 0;
    encoder_btn_count = 0;
    encoder.reset();
  }

}
```
The addition of a set_count() function may have some value, but not worth the effort to add it based on my scenario.

 Thanks for your help.

Bill

**Comment by micromouseonline** [comment]
Glad to help. You solution may well help others. Thanks for sharing.

You may see I edited your comment a little. When putting code in a comment on github, you can enclose it in backticks to get automatic formatting/highlighting. A single backtick for a part of a sentence, three backticks at the beginning and end can enclose a block of code.

Feel free to close the issue if you are happy or I will do so when I remember.

**Comment by sthenge** [comment]
Thank, Peter, for the edit.  Have to say I need to bone up on github if I’m going to continue to contribute.

**Comment by sthenge** [comment]
Bill Stoner941-716-5912On Dec 1, 2023, at 19:14, Peter Harrison ***@***.***> wrote:﻿
Glad to help. You solution may well help others. Thanks for sharing.
You may see I edited your comment a little. When putting code in a comment on github, you can enclose it in backticks to get automatic formatting/highlighting. A single backtick for a part of a sentence, three backticks at the beginning and end can enclose a block of code.
Feel free to close the issue if you are happy or I will do so when I remember.
